### ISSUE TITLE
Mention that Codidact is open source at https://codidact.com/contact

### ISSUE THREAD

**Issue by matkoniecz** [codidact/community-list#19]
**Is your feature request related to a problem? Please describe.**
AFAIK Codidact was supposed to be an open source project, but there is no info about this at https://codidact.com/contact - it looks like something put by company with millions in funding

**Describe the solution you'd like**
Put link to repo at https://codidact.com/contact 

**Describe alternatives you've considered**
Do nothing if GitHub repositories are deliberately hidden and you prefer to get issue reports via Atlassian

**Additional context**
Originally reported at https://github.com/codidact/landing-page/issues/81

**Comment by matkoniecz** [comment]
BTW, I had problem to find this repo. See https://github.com/codidact/landing-page/issues/82

**Comment by cellio** [comment]
Thanks; this is a good point, and yes, Codidact is open-source.
